# Generated by Django 3.0.2 on 2020-02-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('distrito', models.CharField(choices=[('Comas', 'Comas'), ('Los Olivos', 'Los Olivos'), ('San Martín de Porres', 'San Martín de Porres')], max_length=100)),
                ('teléfono', models.CharField(max_length=20)),
                ('Ubicación', models.CharField(max_length=500, null=True)),
                ('costo_por_hora', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('jugadores_por_equipo', models.IntegerField(null=True)),
            ],
        ),
    ]
