# Generated by Django 3.0.2 on 2020-03-02 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('distrito', models.CharField(choices=[('Comas', 'Comas'), ('Los Olivos', 'Los Olivos'), ('San Martín de Porres', 'San Martín de Porres')], max_length=100)),
                ('teléfono', models.CharField(max_length=20)),
                ('Ubicación', models.CharField(max_length=500, null=True)),
                ('costo_por_hora', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('jugadores_por_equipo', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20)),
                ('distrito', models.CharField(choices=[('Comas', 'Comas'), ('Los Olivos', 'Los Olivos'), ('San Martín de Porres', 'San Martín de Porres')], max_length=100)),
                ('posicion', models.CharField(choices=[('Arco', 'Arco'), ('Defensa', 'Defensa'), ('Mediocampo', 'Mediocampo'), ('Ataque', 'Ataque'), ('Mixto', 'Mixto')], max_length=20)),
                ('descripcion', models.TextField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Realizado', 'Realizado'), ('Cancelado', 'Cancelado')], max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('descripcion', models.TextField(null=True)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juegos', to='jobs.Cancha')),
                ('jugadores', models.ManyToManyField(related_name='jugadores', to='jobs.Jugador')),
            ],
        ),
    ]
