# Generated by Django 3.0.2 on 2020-03-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='distrito',
            field=models.CharField(choices=[('Comas', 'Comas'), ('Los Olivos', 'Los Olivos'), ('San Martín de Porres', 'San Martín de Porres')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='posicion',
            field=models.CharField(choices=[('Arco', 'Arco'), ('Defensa', 'Defensa'), ('Mediocampo', 'Mediocampo'), ('Ataque', 'Ataque'), ('Mixto', 'Mixto')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='telefono',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
